site_name: Climate Data Dissemination System
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
nav:
  - Home:
    - About: index.md
  - Operational Procedures:
    - CMIP6: operational_procedure/cmip6.md
    - CMIP6 Plus: operational_procedure/cmip6_plus.md
    - GCModelDev: operational_procedure/gcmodeldev.md
  - Tutorials:
    - Search Inventory: tutorials/search_inventory.md
    - Add a Variable Mapping: tutorials/add_mapping.md
    - Add a Plugin: tutorials/add_plugin.md
  - Developer Documentation:
    - Documentation: developer_documentation/building_documentation.md
    - Release Procedure: developer_documentation/release_procedure.md
    - CDDS Installation: developer_documentation/cdds_installation.md
    - Development Practices:
      - developer_documentation/development_practices.md
      - Coding Guidelines: developer_documentation/coding_guidelines.md
      - Review Guidelines: developer_documentation/review_guidelines.md
      - Working with Github: developer_documentation/github.md
    - Testing:
      - Unit Testing and pytest: developer_documentation/unittests.md
      - Nightly Tests: developer_documentation/nightly_tests.md
      - Mip Convert Functional Tests: developer_documentation/mip_convert_functional_tests.md
  - CDDS Components:
    - convert: cdds_components/convert.md
    - extract: cdds_components/extract.md
    - qc: cdds_components/qc.md
  - API Documentation: reference/
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
extra:
  version:
    provider: mike
plugins:
- search  
- gen-files:
    scripts:
    - scripts/gen_api_docs.py
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: sphinx
- section-index
