site_name: Climate Data Dissemination System
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - content.tabs.link
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home:
    - About: index.md
    - Changelog (CDDS): changes_cdds.md
    - Changelog (Mip Convert): changes_mip_convert.md
  - Operational Procedures:
    - operational_procedure/index.md
    - CMIP6 and CMIP6 Plus: operational_procedure/cmip6.md
    - GCModelDev: 
      -  operational_procedure/gcmodeldev.md
      - GCModelDev HadGEM3-GC31-LL Request: operational_procedure/gcmodeldev_examples/HadGEM3-GC31-LL.md
      - GCModelDev HadGEM3-GC31-LL ensemble class Request: operational_procedure/gcmodeldev_examples/HadGEM3-GC31-LL_envs.md
      - GCModelDev HadGEM3-GC31-MM Request: operational_procedure/gcmodeldev_examples/HadGEM3-GC31-MM.md
      - GCModelDev UKESM1-0-LL Request: operational_procedure/gcmodeldev_examples/UKESM1-0-LL.md
    - Simulation Review Procedure: operational_procedure/sim_review.md
  - Tutorials:
    - Quickstart: tutorials/quickstart.md
    - Search Inventory: tutorials/search_inventory.md
    - Add a Variable Mapping: tutorials/add_mapping.md
    - Add a Mapping Plugin: tutorials/add_mapping_plugin.md
    - Add a Plugin: tutorials/add_plugin.md
    - MIP Convert User Guide: tutorials/mip_convert.md
    - Request Configuration:
      -  tutorials/request/config_request.md
      - Inheritance Section: tutorials/request/inheritance.md
      - Metadata Section: tutorials/request/metadata.md
      - Common Section: tutorials/request/common.md
      - Data Section: tutorials/request/data.md
      - Inventory Section: tutorials/request/inventory.md
      - Conversion Section: tutorials/request/conversion.md
      - Global Attributes Section: tutorials/request/global_attributes.md
      - Misc Section: tutorials/request/misc.md
    - Model Parameters JSON File:
      -  tutorials/json_model_parameter.md
  - Developer Documentation:
    - developer_documentation/developer_documentation.md
    - Deployment:
      - Release Procedure: developer_documentation/deployment/release_procedure.md
      - Installation: developer_documentation/deployment/cdds_installation.md
      - Documentation: developer_documentation/deployment/documentation.md
      - Infrastructure: developer_documentation/deployment/infrastructure.md
    - Development Practices:
      - Coding Guidelines: developer_documentation/coding_guidelines.md
      - Development Workflow: developer_documentation/development_workflow.md
      - Review Process: developer_documentation/review_process.md
      - Managing Conda Environments: developer_documentation/managing_environments.md
      - Documentation: developer_documentation/building_documentation.md
    - Request:
        - Request Architecture: developer_documentation/request/request.md
    - Testing:
      - Unit Testing: developer_documentation/unittests.md
      - Pytest: developer_documentation/pytest.md
      - Nightly Tests: developer_documentation/nightly_tests.md
      - Mip Convert Functional Tests: developer_documentation/mip_convert_functional_tests.md
    - Mapping Plugins:
        - Available Plugins: developer_documentation/mapping_plugins/available_mapping_plugins.md
        - Mapping Plugin Framework: developer_documentation/mapping_plugins/mapping_plugin_framework.md
    - Plugins:
        - Available Plugins: developer_documentation/plugins/available_plugins.md
        - Plugin Framework: developer_documentation/plugins/plugin_framework.md
  - CDDS Components:
    - cdds_components/index.md
    - convert: cdds_components/convert.md
    - extract: cdds_components/extract.md
    - qc: cdds_components/qc.md
    - transfer: cdds_components/transfer.md
  - API Documentation: reference/
  - Mappings: mappings/index.md
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
extra:
  version:
    provider: mike
plugins:
- search  
- gen-files:
    scripts:
    - scripts/changes.py
    - scripts/mappings.py
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: sphinx
- section-index
