#!/bin/bash

parse_options() {
  # Parse all arguments/options of the command
  for i in "$@"
  do
    case $i in
    --parent=*)
      PARENT_BRANCH="${i#*=}"
      shift
      ;;
    --year=*)
      NEW_YEAR="${i#*=}"
      shift
      ;;
    -h|--help)
      HELP=YES
      shift
      ;;
    *)
      # unknown option
      ;;
    esac
  done

  # Set defaults
  if [ -z "$PARENT_BRANCH" ]
  then
    PARENT_BRANCH="main"
  fi

  if [ -z "$NEW_YEAR" ]
  then
    # Get current year from system
    NEW_YEAR=`date +'%Y'`
  fi
}

set_work_branch() {
  # Get URL of current branch
  WORK_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
  WORK_BRANCH="origin/${WORK_BRANCH_NAME}"
}

do_upgrade() {
  echo "Working Branch: ${WORK_BRANCH}"
  echo "Parent Branch: ${PARENT_BRANCH}"
  echo "New year: ${NEW_YEAR}"

  filesToUpdate=$(git diff ${WORK_BRANCH}  ${PARENT_BRANCH} | diffstat | sed 's/[ \t]*|.*$//')
  echo "${filesToUpdate}"
  filePaths=($(echo "$filesToUpdate" | tr ' ' '\n'))

  for file in "${filePaths[@]}"
  do
    if test -f "$file"; then
      echo "Upgrade copyright in $file"
      sed -i -E "s/Copyright ([0-9]+)-[0-9]+,/Copyright \\1-${NEW_YEAR},/g" $file
      sed -i -E "s/British Crown ([0-9]+)-[0-9]+,/British Crown \\1-${NEW_YEAR},/g" $file

      sed -i -E "s/Copyright ([0-9]+),/Copyright \\1-${NEW_YEAR},/g" $file
      sed -i -E "s/British Crown ([0-9]+),/British Crown \\1-${NEW_YEAR},/g" $file
    fi
  done
}

show_help() {
    programname=$0
    echo "Usage: $programname [-h] [--parent] [--year=newyear]"
    echo "  --parent        parent branch name if not main"
    echo "  --year          year to upgrade to"
    echo "  -h/--help       display help"
}

parse_options "$@"
if [ -n "$HELP" ]
then
  show_help
else
  set_work_branch
  do_upgrade
fi
