#!/usr/bin/env python3
# (C) British Crown Copyright 2026, Met Office.
# Please see LICENSE.md for license details.
"""Converts the standard CDDS data structure generated by `create_cdds_directory_structure` to the esgf compliant
format.

This should be used only when all processing has completed. Using the -m flag will **move** all data files to the new
structure, using no flag will generate symbolic links.

WARNING: Once data has been **moved** out of the CDDS structure transfer tasks in workflows may fail. If intending to
use `cdds_transfer` to archive to MASS please ensure this is completed before moving any files.
"""

import logging
import argparse
import os

from pathlib import Path
from datetime import datetime

from cdds.common.request.request import read_request, Request
from cdds.common.plugins.plugins import PluginStore, CddsPlugin
from cdds.common import configure_logger, run_command
from cdds.common.request.validations.cv_validators import CVValidatorFactory

from mip_convert.configuration.cv_config import CVConfig


def arg_parser() -> argparse.Namespace:
    """Creates an argument parser to take source file paths from the command line.

    Returns
    -------
    argparse.Namespace
        The argument parser to handle source file paths.

    """
    parser = argparse.ArgumentParser(description="Delete a workflow metadata configuration file and all associated "
                                     "files.")
    parser.add_argument("request", help="The full path to the request file used to generate the data.")
    parser.add_argument("output_root_dir", help="The output dir used as the root for the esgf data structure.")
    parser.add_argument("-m", "--move", action="store_true",
                        help="Move files to the new data structure rather than using a symbolic link.")

    return parser.parse_args()


def get_logger(request: Request, plugin) -> logging.Logger:
    """Configures and set up the log name ready for use.

    Parameters
    ----------
    request: Request
        The request configuration file.
    plugin:
        The plugin.

    Returns
    -------
    logging.Logger
        The logger.
    """
    # Create the full log path and filename
    prepare_dir = Path(plugin.proc_directory(request)) / "prepare" / "log"
    if not Path.exists(prepare_dir):
        raise FileNotFoundError(f"Prepare directory: '{prepare_dir}' does not exist.")
    log_name = prepare_dir / f"arrange_cdds_to_esgf"

    configure_logger(str(log_name), "DEBUG", append_log=True)

    return logging.getLogger(__name__)


def create_esgf_root_dir(plugin: CddsPlugin, request: Request, output_root: str) -> str:
    """Creates an empty, new esgf compliant root path structure.

    Parameters
    ----------
    plugin: CddsPlugin
        The CDDS plugin.
    request: Request
        The CDDS request.
    output_root: str
            The base directory that the esgf compliant directory structure will be created within.

    Returns
    -------
    str
        The esgf compliant root directory structure.
    """
    cv_to_request_attr_mapping = {
        "drs_specs": request.netcdf_global_attributes.attributes.get("drs_specs"),
        "mip_era": request.metadata.mip_era,
        "activity_id": request.metadata.mip,
        "institution_id": request.metadata.institution_id,
        "source_id": request.metadata.model_id,
        "experiment_id": request.metadata.experiment_id,
        "variant_label": request.metadata.variant_label,
    }
    cv_path = os.path.join(plugin.mip_table_dir(), '{}_CV.json'.format(request.metadata.mip_era))
    CVValidatorFactory.path_validator()(cv_path)
    cv_config = CVConfig(cv_path)

    esgf_root_dir_attrs = [output_root]
    for attr in cv_config.drs_directory_template.split("/"):
        attr = attr.lstrip("<").rstrip(">")
        # Stop forming the root dir if the loop encounters any variable specific attributes
        if attr in ("region", "frequency", "variable_id", "branding_suffix", "grid_label", "version"):
            break
        try:
            esgf_root_dir_attrs.append(cv_to_request_attr_mapping.get(attr).strip())
        except AttributeError as err:
            if "'NoneType' object has no attribute 'strip'" in str(err):
                raise RuntimeError(f"Key path attribute `{attr}` missing from request file.")
            else:
                raise AttributeError(err)

    return "/".join(esgf_root_dir_attrs)


def rearrange_files(files: list, esgf_path_root: str, command: str) -> None:
    """Rearranges all files into the new esgf compliant directory structure.

    Parameters
    ----------
    files: list
        The files to rearrange.
    esgf_path_root: str
        The esgf compliant root directory structure as created by `create_esgf_root_dir()`.
    command: str
        'mv' or 'ln -s'. Determines whether files will be moved to the new structure or symbolically linked.
    """
    logger = logging.getLogger(__name__)
    version = f"v{datetime.today().strftime('%Y%m%d')}"
    for old_path in files:
        filename = old_path.split("/")[-1]  # This already exists in the expected format

        # Construct new ESGF compliant path
        var_id, branding, freq, region, grid = filename.split("_")[:5]
        new_path = esgf_path_root + f"/{region}/{freq}/{var_id}/{branding}/{grid}/{version}/"

        # Rearrange files
        run_command(f"mkdir -p {new_path}".split())
        logger.info(f"{command} {old_path} {new_path}")
        try:
            run_command(f"{command} {old_path} {new_path}".split())
        except RuntimeError as e:
            # Except file aleady exists runtime error only (occurs for symbolic links)
            if ": File exists" in str(e):
                logger.info(f"File already exists {new_path}{filename}, continuing")
            else:
                raise RuntimeError(e)


def main_arrange_to_esgf():
    """Main."""
    args = arg_parser()
    request = read_request(args.request)
    plugin = PluginStore.instance().get_plugin()
    logger = get_logger(request, plugin)

    cdds_output_data_path = os.path.join(plugin.data_directory(request), "output")
    logger.info(f"Looking for files in {cdds_output_data_path}/...")
    files = run_command(['find', cdds_output_data_path, '-type', 'f', '-name', '*.nc']).split("\n")
    files = [f for f in files if f.strip()]  # Remove any blank items
    logger.info(f"Found {len(files)} files in {cdds_output_data_path}...")

    esgf_path_root = create_esgf_root_dir(plugin, request, args.output_root_dir)

    if args.move:
        logger.info(f"Moving {len(files)} to root path {esgf_path_root}")
        rearrange_files(files, esgf_path_root, "mv")
    else:
        logger.info(f"Symbolic linking {len(files)} to root path {esgf_path_root}")
        rearrange_files(files, esgf_path_root, "ln -s")
