#!/bin/bash

if [ -z "$*" ]
then
      export TEST_PACKAGES=${CDDS_PACKAGES}
else
      export TEST_PACKAGES=$*
fi

echo "Running tests for packages:"
echo ${TEST_PACKAGES}

# currently (February 2020, v1.3.2) if we run all the test attributes together,
# then some of the tests fail (primarily data_request tests), so we need to run
# tests for each attribute separately. Once the cause of the errors is
# found and fixed, this can be simplified by simply passing the
# CDDS_TEST_ATTRIBUTES list directly to the nosetests command.
for PACKAGE in ${TEST_PACKAGES}
do
    for ATTR in ${CDDS_TEST_ATTRIBUTES}
    do
       echo "Running ${PACKAGE}-${ATTR} tests"
       nosetests -s -a ${ATTR} ${PACKAGE}
    done
done

