#!/bin/bash

if [ -z "$*" ]
then
      export TEST_PACKAGES=${CDDS_PACKAGES}
else
      export TEST_PACKAGES=$*
fi

echo "Running tests for packages:"
echo ${TEST_PACKAGES}

nosetests -s -a ${CDDS_TEST_NOATTRIBUTES} ${TEST_PACKAGES} --with-doctest

# currently (February 2020, v1.3.2) if we run all the test attributes together,
# then some of the tests fail (primarily data_request tests), so we need to run
# tests for each attribute separately. Once the cause of the errors is
# found and fixed, this can be simplified by simply omitting the attributes (-a)
# flag from the nosetests command to run all tests.
for PACKAGE in ${TEST_PACKAGES}
do
    for ATTR in ${CDDS_TEST_ATTRIBUTES}
    do
       echo "Running ${PACKAGE}-${ATTR} tests"
       nosetests -s -a ${ATTR} ${PACKAGE}
    done
done
