#!/bin/bash

if [ -z "$*" ]
then
      export TEST_PACKAGES=${CDDS_PACKAGES}
else
      export TEST_PACKAGES=$*
fi

echo "Running tests for packages:"
echo ${TEST_PACKAGES}

# 'style' is not included in list $CDDS_TEST_NOATTRIBUTES, so that
# code style tests will still run with the quick tests
nosetests -s -a ${CDDS_TEST_NOATTRIBUTES} ${TEST_PACKAGES} --with-doctest
