# (C) British Crown Copyright 2018-2025, Met Office.
# Please see LICENSE.md for license details.
"""This module contains common test data used within CDDS Prepare."""

ATMOS_ENABLED = {
    'Amon_tas_0_0': {
        'cmor': 'tas',
        'dom_name': 'DIAG',
        'enabled': True,
        'item': '236',
        'package': 'CMIP6-core',
        'present': True,
        'priority': 'dr1.0',
        'section': '03',
        'sheet_name': 'Amon',
        'stash': 'm01s03i236',
        'tim_name': 'TMONMN',
        'use_name': 'UP5'},
    'Eday_ua_0_0': {
        'cmor': 'ua',
        'dom_name': 'PLEV19',
        'enabled': True,
        'item': '201',
        'package': 'CMIP6-core',
        'present': True,
        'priority': 'dr1.0',
        'section': '30',
        'sheet_name': 'Eday',
        'stash': 'm01s30i201',
        'tim_name': 'TDAYMN',
        'use_name': 'UP6'},
    'Eday_ua_1_0': {
        'cmor': 'ua',
        'dom_name': 'PLEV19',
        'enabled': True,
        'item': '301',
        'package': 'CMIP6-core',
        'present': True,
        'priority': 'dr1.0',
        'section': '30',
        'sheet_name': 'Eday',
        'stash': 'm01s30i301',
        'tim_name': 'TDAYMN',
        'use_name': 'UP6'},
    'Eday_ua_2_0': {
        'cmor': 'ua',
        'dom_name': 'PLEV19',
        'enabled': True,
        'item': '202',
        'package': 'CMIP6-core',
        'present': True,
        'priority': 'dr1.0',
        'section': '30',
        'sheet_name': 'Eday',
        'stash': 'm01s30i202',
        'tim_name': 'TDAYMN',
        'use_name': 'UP6'},
    'day_pr_0_0': {
        'cmor': 'pr',
        'dom_name': 'DIAG',
        'enabled': True,
        'item': '216',
        'package': 'CMIP6-core',
        'present': True,
        'priority': 'dr1.0',
        'section': '05',
        'sheet_name': 'day',
        'stash': 'm01s05i216',
        'tim_name': 'TDAYMN',
        'use_name': 'UP6'},
    'Emon_rls_0_0': {
        'cmor': 'rls',
        'dom_name': 'DIAG',
        'enabled': True,
        'item': '201',
        'package': 'CMIP6-core',
        'present': True,
        'priority': 'dr1.0',
        'section': '02',
        'sheet_name': 'Emon',
        'stash': 'm01s02i201',
        'tim_name': 'TMONMN',
        'use_name': 'UP5'},
    'Emon_rls_1_0': {
        'cmor': 'rls',
        'dom_name': 'DIAG',
        'enabled': True,
        'item': '205',
        'package': 'CMIP6-core',
        'present': True,
        'priority': 'dr1.0',
        'section': '02',
        'sheet_name': 'Emon',
        'stash': 'm01s02i205',
        'tim_name': 'TMONMN',
        'use_name': 'UP5'},
    'Emon_rls_2_0': {
        'cmor': 'rls',
        'dom_name': 'DIAG',
        'enabled': True,
        'item': '332',
        'package': 'CMIP6-core',
        'present': True,
        'priority': 'dr1.0',
        'section': '03',
        'sheet_name': 'Emon',
        'stash': 'm01s03i332',
        'tim_name': 'TMONMN',
        'use_name': 'UP5'}}

OCEAN_ENABLED = {
    'Omon/tos': {
        'enabled': [True]},
    'Oday/sos': {
        'enabled': [True]}}

TEST_RV_DICT = {
    'checksum': 'md5: cf465188aa110808e940b2e8041b1ce4',
    'data_request_version': '01.00.29',
    'experiment_id': 'ssp126',
    'history': [{'comment': 'Requested variables file created.',
                 'time': '2019-01-01T00:00:00.000000'}],
    'metadata': {'data_request_code_version': '01.00.29',
                 'data_request_files': {
                     'DOC_DIR': '/dummy/path',
                     'PACKAGE_DIR': '/dummy/path',
                     'blockSchemaFile': '/dummy/path/file.csv',
                     'defaultConfigPath': '/dummy/path/file.xml',
                     'defaultDreqPath': '/dummy/path/file.xml',
                     'defaultManifestPath': '/dummy/path/file.txt'},
                 'data_request_version': '01.00.29',
                 'end year': '2100.0',
                 'ensemble size': [1],
                 'experiment description': 'Dummy description',
                 'experiment title': 'update of RCP2.6 based on SSP1',
                 'experiment_id': 'ssp126',
                 'experiment_uid': 'f16f6188-dd9e-11e6-b89b-ac72891c3257',
                 'mip': 'ScenarioMIP',
                 'number of start dates': 1,
                 'start year': '2015.0',
                 'tier': [1],
                 'years per start': 86},
    'mip': 'ScenarioMIP',
    'mip_era': 'CMIP6',
    'model_id': 'UKESM1-0-LL',
    'model_type': 'AOGCM AER BGC CHEM',
    'production_info': 'Produced using CDDS Prepare',
    'requested_variables': [{'active': True,
                             'cell_methods': 'area: time: mean',
                             'comments': [],
                             'dimensions': ['longitude',
                                            'latitude',
                                            'time'],
                             'frequency': 'mon',
                             'in_mappings': True,
                             'in_model': True,
                             'label': 'pr',
                             'miptable': 'Amon',
                             'priority': 1},
                            {'active': True,
                             'cell_methods': 'area: time: mean',
                             'comments': [],
                             'dimensions': ['longitude',
                                            'latitude',
                                            'height2m',
                                            'time'],
                             'frequency': 'mon',
                             'in_mappings': True,
                             'in_model': True,
                             'label': 'tas',
                             'miptable': 'Amon',
                             'priority': 1},
                            {'active': True,
                             'cell_methods': 'area: time: mean',
                             'comments': [],
                             'dimensions': ['longitude',
                                            'latitude',
                                            'height10m',
                                            'time'],
                             'frequency': 'mon',
                             'in_mappings': True,
                             'in_model': True,
                             'label': 'uas',
                             'miptable': 'Amon',
                             'priority': 1},
                            {'active': True,
                             'cell_methods': 'area: time: mean',
                             'comments': [],
                             'dimensions': ['longitude',
                                            'latitude',
                                            'height10m',
                                            'time'],
                             'frequency': 'mon',
                             'in_mappings': True,
                             'in_model': True,
                             'label': 'vas',
                             'miptable': 'Amon',
                             'priority': 1}],
    'status': 'ok',
    'suite_branch': 'cdds',
    'suite_id': 'u-be509',
    'suite_revision': '106109'}

SELECT_DEACTIVATE_HISTORY_COMMENT = {
    'comment': 'User selected a subset of variables for processing.',
    'override': False,
    'time': '',
    'type': 'deactivate',
    'variables_affected': {'Amon': ['pr', 'uas', 'vas']}
}

SELECT_CHANGE_RULES = [{'miptable': 'Amon', 'label': 'pr'},
                       {'miptable': 'Amon', 'label': 'uas'},
                       {'miptable': 'Amon', 'label': 'vas'},
                       ]

TEST_RV_VARS_AFTER_SELECT = [
    {'active': False,
     'cell_methods': 'area: time: mean',
     'comments': [],
     'dimensions': ['longitude',
                    'latitude',
                    'time'],
     'frequency': 'mon',
     'in_mappings': True,
     'in_model': True,
     'label': 'pr',
     'miptable': 'Amon',
     'priority': 1},
    {'active': True,
     'cell_methods': 'area: time: mean',
     'comments': [],
     'dimensions': ['longitude',
                    'latitude',
                    'height2m',
                    'time'],
     'frequency': 'mon',
     'in_mappings': True,
     'in_model': True,
     'label': 'tas',
     'miptable': 'Amon',
     'priority': 1},
    {'active': False,
     'cell_methods': 'area: time: mean',
     'comments': [],
     'dimensions': ['longitude',
                    'latitude',
                    'height10m',
                    'time'],
     'frequency': 'mon',
     'in_mappings': True,
     'in_model': True,
     'label': 'uas',
     'miptable': 'Amon',
     'priority': 1},
    {'active': False,
     'cell_methods': 'area: time: mean',
     'comments': [],
     'dimensions': ['longitude',
                    'latitude',
                    'height10m',
                    'time'],
     'frequency': 'mon',
     'in_mappings': True,
     'in_model': True,
     'label': 'vas',
     'miptable': 'Amon',
     'priority': 1}
]

DEACTIVATE_COMMENT = ('deactivated 2019-01-02T00:00:00 - '
                      'unit test test_apply_activate_deactivate')

VARIABLE_DIRECTORY_PATH = '/foo/bar'

DUMMY_DEACTIVATION_RULES = {
    "*": [
        ["Omon/zhalfo",
         "Deactivate failing variable that causes problems for CDDS Convert (#838, #899, #712)"],
        ["CFmon/clcalipso", "CFday/clcalipso", "CFmon/clhcalipso", "CFday/clhcalipso",
         "CFmon/cllcalipso", "CFday/cllcalipso", "CFmon/clmcalipso", "CFday/clmcalipso",
         "CFmon/cltcalipso", "CFday/cltcalipso", "Emon/parasolRefl", "Eday/parasolRefl",
         "Emon/reffclic", "Emon/reffclis", "Emon/reffclwc", "Emon/reffclws",
         "E3hrPt/cllcalipso", "E3hrPt/clmcalipso", "E3hrPt/clhcalipso", "E3hrPt/cltcalipso",
         "E3hrPt/clisccp",
         "Deactivate all COSP calipso variables due to known issue (#1465)"],
        ["CFmon/tnta", "CFmon/tnhusa", "CFmon/tnhusmp", "CFmon/tntmp",
         "Deactivate variables that can only be produced using the CFMIP STASH setup"
         ],
        ["AERmon/wetbc", "AERmon/wetoa", "AERmon/wetss",
         "Deactivate variables with STASH missing from UKESM suites and incorrect atmos_dictionary entries"]
    ],
    "piControl": [
        [
            "day/wap", "EdayZ/epfy", "EdayZ/epfz", "Emon/intuaw", "Emon/intvaw", "Eday/wap",
            "Amon/wap", "EmonZ/epfy", "EmonZ/epfz", "6hrPlev/wap4", "E3hrPt/wap7h",
            "Omon/cfc11", "Omon/cfc12", "Omon/sf6", "Omon/fgcfc11", "Omon/fgcfc12", "Omon/fgsf6",
            "Oyr/cfc11", "Oyr/cfc12", "Oyr/sf6", "Oyr/fgcfc11", "Oyr/fgcfc12", "Oyr/fgsf6",
            "AERmon/oh", "AERmonZ/oh", "AERmonZ/vmrox", "CFday/wap500",
            "Known faulty variables in piControl"
        ]
    ]
}
