# (C) British Crown Copyright 2019-2021, Met Office.
# Please see LICENSE.md for license details.
"""
The :mod:`constants` module contains constants (values that should never
be changes by a user and exist for readability and maintainability
purposes) related to the ``data_request_interface`` sub-package.
"""
CMORVAR_ATTR_MAPPINGS = {
    'comment': 'description',
    'variable_name': 'label',
    'default_priority': 'defaultPriority',
    'frequency': 'frequency',
    'long_name': 'title',
    'mip_table': 'mipTable',
    'modeling_realm': 'modeling_realm',
    'positive': 'positive',
    'type': 'type',
    'vid': 'vid',
}
# The 'DATA_REQUEST_LINKAGES' dictionary connects the data request
# object types with the properties they have that links them to other
# data request objects. This is used to build the network of DreqNodes.
DATA_REQUEST_LINKAGES = {
    'experiment': ['egid', 'mip'],
    'exptgroup': [],
    'mip': [],
    'requestItem': ['esid', 'rlid', 'tslice'],
    'timeSlice': [],
    'requestLink': ['refid'],
    'requestVarGroup': [],
    'requestVar': ['vid', 'vgid'],
    'CMORvar': [],
}
# Metadata to record in 'retrieve_data_request_variables'.
# {data request property name: key to record information under}
EXPERIMENT_METADATA_TO_RECORD = {
    'description': 'experiment description',
    'endy': 'end year',
    'ensz': 'ensemble size',
    'mip': 'mip',
    'nstart': 'number of start dates',
    'starty': 'start year',
    'tier': 'tier',
    'title': 'experiment title',
    'uid': 'experiment_uid',
    'yps': 'years per start',
}
# The following items were found by searching through the attributes of
# the dreq module and picking out strings that contain the current
# version number. This may break if dreqPy changes structure.
FIELDS_TO_ALTER_PRIOR_TO_LOAD = {
    'DOC_DIR': 'dreqPy/docs',
    'blockSchemaFile': 'dreqPy/docs/BlockSchema.csv',
    'defaultDreqPath': 'dreqPy/docs/dreq.xml',
    'defaultConfigPath': 'dreqPy/docs/dreq2Defn.xml',
    'defaultManifestPath': 'dreqPy/docs/dreqManifest.txt',
    'PACKAGE_DIR': 'dreqPy',
}
# Remarks objects appear in various places, presumably as place holders.
# These must be ignored.
IGNORED_NODE_TYPES = ['remarks']
# Number used to indicate that a request relates to all ensemble members
# of an experiment.
MAX_ENSEMBLE_SIZE = 1000
STRUCTURE_ATTR_MAPPINGS = {
    'cell_measures': 'cell_measures',
    'cell_methods': 'cell_methods',
}
VARIABLE_ATTR_MAPPINGS = {
    'output_variable_name': 'label',
    'description': 'description',
    'standard_name': 'sn',
    'units': 'units',
}
# Routes for walking the data request.
WALK_ROUTE_MAIN = ['CMORvar', 'requestVar', 'requestVarGroup',
                   'requestLink', 'requestItem']
WALK_ROUTE_A = WALK_ROUTE_MAIN + ['mip', 'experiment']
WALK_ROUTE_B = WALK_ROUTE_MAIN + ['exptgroup', 'experiment']
WALK_ROUTE_C = WALK_ROUTE_MAIN + ['experiment']

# 'KNOWN_GOOD_VARIABLES' is a dictionary keyed first by a tuple describing the
# data request versions being used then by the MIP table, with the key being a
# list of variables which are known to be good.  For example, if the
# 'cell_methods' of a particular 'MIP requested variable' has changed,
# but this doesn't change how it is interpreted or produced, an entry
# should be added to approve the 'MIP requested variable' for a given
# version of the data request.
KNOWN_GOOD_VARIABLES = {
    ('01.00.10', '01.00.29'): {
        '6hrLev': ['ec550aer', 'pfull'],
        '6hrPlevPt': ['vortmean'],
        'Amon': ['fco2antt', 'fco2fos', 'fco2nat'],
        'E3hrPt': ['parasolRefl'],
        'Eday': ['hursminCrop', 'mlotst', 't20d'],
        'Emon': ['evspsblpot', 'hus', 'sfcWindmax', 'sweLut', 'thetaot',
                 'thetaot2000', 'thetaot300', 'thetaot700',
                 'gppLut', 'hflsLut', 'hfssLut', 'hussLut', 'laiLut',
                 'nppLut', 'rlusLut', 'rsusLut', 'tasLut', 'tslsiLut',
                 'grassFracC3', 'grassFracC4'],
        'EmonZ': ['sltbasin'],
        'Ofx': ['areacello', 'deptho', 'hfgeou'],
        'Omon': ['bfeos', 'bsios', 'chldiatos', 'chlmiscos', 'dfeos',
                 'hfx', 'hfy', 'hfbasin', 'hfbasinpadv', 'hfbasinpmadv',
                 'hfbasinpmdiff', 'htovgyre', 'htovovrt',
                 'intpcalcite', 'intpoc', 'intppmisc', 'msftyzmpa',
                 'no3os', 'o2os', 'o2satos', 'phynos', 'phypos', 'physios',
                 'ponos', 'popos', 'sios',
                 'sltovgyre', 'sltovovrt'],
        'SIday': ['sispeed', 'sitemptop', 'sithick', 'sitimefrac'],
        'SImon': ['sfdsi', 'siage', 'sicompstren', 'sidconcdyn', 'sidconcth',
                  'sidmassdyn', 'sidmassevapsubl', 'sidmassgrowthbot',
                  'sidmassgrowthwat', 'sidmasslat', 'sidmassmeltbot',
                  'sidmassmelttop', 'sidmasssi', 'sidmassth', 'sidragtop',
                  'sifb', 'siflcondbot', 'siflcondtop', 'siflfwbot',
                  'siflfwdrain', 'sifllatstop', 'sifllwdtop', 'sifllwutop',
                  'siflsenstop', 'siflsensupbot', 'siflswdtop', 'siflswutop',
                  'sihc', 'simass', 'sipr', 'sirdgconc', 'sirdgthick',
                  'sisaltmass', 'sisnconc', 'sisnhc', 'sisnmass', 'sispeed',
                  'sistrxubot', 'sistryubot', 'sitempbot', 'sitemptop',
                  'sithick', 'sitimefrac', 'sivol', 'sndmassdyn',
                  'sndmassmelt', 'sndmasssi', 'sndmasssnf'],
        'fx': ['areacella', 'mrsofc']},
    ('01.00.10', '01.00.31beta'): {
        '6hrLev': ['ec550aer', 'pfull'],
        '6hrPlevPt': ['vortmean'],
        'Amon': ['fco2antt', 'fco2fos', 'fco2nat'],
        'E3hrPt': ['parasolRefl'],
        'Eday': ['hursminCrop', 'mlotst', 't20d'],
        'Emon': ['evspsblpot', 'hus', 'sfcWindmax', 'sweLut',
                 'thetaot', 'thetaot2000', 'thetaot300', 'thetaot700',
                 'vegHeightPasture',
                 'gppLut', 'hflsLut', 'hfssLut', 'hussLut', 'laiLut', 'nppLut',
                 'rlusLut', 'rsusLut', 'tasLut', 'tslsiLut', 'grassFracC3',
                 'grassFracC4'],
        'EmonZ': ['sltbasin'],
        'Ofx': ['areacello', 'deptho', 'hfgeou'],
        'Omon': ['bfeos', 'bsios', 'chldiatos', 'chlmiscos', 'dfeos',
                 'hfx', 'hfy', 'hfbasin', 'hfbasinpadv', 'hfbasinpmadv',
                 'hfbasinpmdiff', 'htovgyre', 'htovovrt',
                 'intpcalcite', 'intpoc', 'intppmisc', 'masscello',
                 'msftyzmpa',
                 'no3os', 'o2os', 'o2satos', 'phynos', 'phypos', 'physios',
                 'ponos', 'popos', 'sios', 'sltovgyre', 'sltovovrt', 'wmo'],
        'SIday': ['sispeed', 'sitemptop', 'sithick', 'sitimefrac'],
        'SImon': ['sfdsi', 'siage', 'sicompstren', 'sidconcdyn', 'sidconcth',
                  'sidmassdyn', 'sidmassevapsubl', 'sidmassgrowthbot',
                  'sidmassgrowthwat', 'sidmasslat', 'sidmassmeltbot',
                  'sidmassmelttop', 'sidmasssi', 'sidmassth', 'sidragtop',
                  'sifb', 'siflcondbot', 'siflcondtop', 'siflfwbot',
                  'siflfwdrain', 'sifllatstop', 'sifllwdtop', 'sifllwutop',
                  'siflsenstop', 'siflsensupbot', 'siflswdtop', 'siflswutop',
                  'sihc', 'simass', 'sipr', 'sirdgconc', 'sirdgthick',
                  'sisaltmass', 'sisnconc', 'sisnhc', 'sisnmass', 'sispeed',
                  'sistrxubot', 'sistryubot', 'sitempbot', 'sitemptop',
                  'sithick', 'sitimefrac', 'sivol', 'sndmassdyn',
                  'sndmassmelt', 'sndmasssi', 'sndmasssnf'],
        'fx': ['areacella', 'mrsofc']},
    ('01.00.10', '01.00.32'): {
        '6hrLev': ['ec550aer', 'pfull'],
        '6hrPlevPt': ['vortmean'],
        'Amon': ['fco2antt', 'fco2fos', 'fco2nat'],
        'E3hrPt': ['parasolRefl'],
        'Eday': ['hursminCrop', 'mlotst', 't20d'],
        'Emon': ['evspsblpot', 'hus', 'sfcWindmax', 'sweLut',
                 'thetaot', 'thetaot2000', 'thetaot300', 'thetaot700',
                 'vegHeightPasture',
                 'gppLut', 'hflsLut', 'hfssLut', 'hussLut', 'laiLut', 'nppLut',
                 'rlusLut', 'rsusLut', 'tasLut', 'tslsiLut', 'grassFracC3',
                 'grassFracC4'],
        'EmonZ': ['sltbasin'],
        'Ofx': ['areacello', 'deptho', 'hfgeou'],
        'Omon': ['bfeos', 'bsios', 'chldiatos', 'chlmiscos', 'dfeos',
                 'hfx', 'hfy', 'hfbasin', 'hfbasinpadv', 'hfbasinpmadv',
                 'hfbasinpmdiff', 'htovgyre', 'htovovrt',
                 'intpcalcite', 'intpoc', 'intppmisc', 'masscello',
                 'msftyzmpa',
                 'no3os', 'o2os', 'o2satos', 'phynos', 'phypos', 'physios',
                 'ponos', 'popos', 'sios', 'sltovgyre', 'sltovovrt', 'wmo'],
        'SIday': ['sispeed', 'sitemptop', 'sithick', 'sitimefrac'],
        'SImon': ['sfdsi', 'siage', 'sicompstren', 'sidconcdyn', 'sidconcth',
                  'sidmassdyn', 'sidmassevapsubl', 'sidmassgrowthbot',
                  'sidmassgrowthwat', 'sidmasslat', 'sidmassmeltbot',
                  'sidmassmelttop', 'sidmasssi', 'sidmassth', 'sidragtop',
                  'sifb', 'siflcondbot', 'siflcondtop', 'siflfwbot',
                  'siflfwdrain', 'sifllatstop', 'sifllwdtop', 'sifllwutop',
                  'siflsenstop', 'siflsensupbot', 'siflswdtop', 'siflswutop',
                  'sihc', 'simass', 'sipr', 'sirdgconc', 'sirdgthick',
                  'sisaltmass', 'sisnconc', 'sisnhc', 'sisnmass', 'sispeed',
                  'sistrxubot', 'sistryubot', 'sitempbot', 'sitemptop',
                  'sithick', 'sitimefrac', 'sivol', 'sndmassdyn',
                  'sndmassmelt', 'sndmasssi', 'sndmasssnf'],
        'fx': ['areacella', 'mrsofc']},
    ('01.00.17', '01.00.29'): {
        '6hrLev': ['pfull'],
        'Amon': ['fco2antt', 'fco2fos', 'fco2nat'],
        'E3hrPt': ['parasolRefl'],
        'Eday': ['hursminCrop', 'mlotst', 't20d'],
        'Emon': ['sweLut', 'thetaot', 'thetaot2000', 'thetaot300',
                 'thetaot700', 'vegHeight', 'gppLut', 'hflsLut', 'hfssLut',
                 'hussLut', 'laiLut', 'nppLut', 'rlusLut', 'rsusLut', 'tasLut',
                 'tslsiLut', 'grassFracC3', 'grassFracC4'],
        'EmonZ': ['sltbasin'],
        'Ofx': ['deptho', 'hfgeou'],
        'Omon': ['bfeos', 'bsios', 'chldiatos', 'chlmiscos', 'dfeos',
                 'intdic', 'intpbfe', 'intpbsi', 'intpbn', 'intpbp',
                 'intpp', 'intppdiat',
                 'hfbasin', 'hfbasinpadv', 'hfbasinpmadv', 'hfbasinpmdiff',
                 'htovgyre', 'htovovrt', 'intpcalcite', 'intpoc', 'intppmisc',
                 'msftyzmpa',
                 'no3os', 'o2os', 'o2satos', 'phynos', 'phypos', 'physios',
                 'ponos', 'popos', 'sios',
                 'sltovgyre', 'sltovovrt'],
        'SIday': ['sispeed', 'sitemptop', 'sithick', 'sitimefrac'],
        'SImon': ['sfdsi', 'siage', 'sicompstren', 'sidconcdyn', 'sidconcth',
                  'sidmassdyn', 'sidmassevapsubl', 'sidmassgrowthbot',
                  'sidmassgrowthwat', 'sidmasslat', 'sidmassmeltbot',
                  'sidmassmelttop', 'sidmasssi', 'sidmassth', 'sidragtop',
                  'sifb', 'siflcondbot', 'siflcondtop', 'siflfwbot',
                  'siflfwdrain', 'sifllatstop', 'sifllwdtop', 'sifllwutop',
                  'siflsenstop', 'siflsensupbot', 'siflswdtop', 'siflswutop',
                  'sihc', 'simass', 'sipr', 'sirdgconc', 'sirdgthick',
                  'sisaltmass', 'sisnconc', 'sisnhc', 'sisnmass', 'sispeed',
                  'sistrxubot', 'sistryubot', 'sitempbot', 'sitemptop',
                  'sithick', 'sitimefrac', 'sivol', 'sndmassdyn',
                  'sndmassmelt', 'sndmasssi', 'sndmasssnf']},
    ('01.00.17', '01.00.31beta'): {
        '6hrLev': ['pfull'],
        'Amon': ['fco2antt', 'fco2fos', 'fco2nat'],
        'E3hrPt': ['parasolRefl'],
        'Eday': ['hursminCrop', 'mlotst', 't20d'],
        'Emon': ['sweLut', 'thetaot', 'thetaot2000', 'thetaot300',
                 'thetaot700', 'vegHeight', 'vegHeightPasture',
                 'gppLut', 'hflsLut', 'hfssLut', 'hussLut', 'laiLut', 'nppLut',
                 'rlusLut', 'rsusLut', 'tasLut', 'tslsiLut', 'grassFracC3',
                 'grassFracC4'],
        'EmonZ': ['sltbasin'],
        'LImon': ['sftgif'],
        'Ofx': ['deptho', 'hfgeou'],
        'Omon': ['bfeos', 'bsios', 'chldiatos', 'chlmiscos', 'dfeos',
                 'intdic', 'intpbfe', 'intpbsi', 'intpp', 'intpbn', 'intpbp',
                 'intppdiat',
                 'hfbasin', 'hfbasinpadv', 'hfbasinpmadv', 'hfbasinpmdiff',
                 'htovgyre', 'htovovrt', 'intpcalcite', 'intpoc', 'intppmisc',
                 'masscello', 'msftyzmpa',
                 'no3os', 'o2os', 'o2satos', 'phynos', 'phypos', 'physios',
                 'ponos', 'popos', 'sios',
                 'sltovgyre', 'sltovovrt', 'wmo'],
        'SIday': ['sispeed', 'sitemptop', 'sithick', 'sitimefrac'],
        'SImon': ['sfdsi', 'siage', 'sicompstren', 'sidconcdyn', 'sidconcth',
                  'sidmassdyn', 'sidmassevapsubl', 'sidmassgrowthbot',
                  'sidmassgrowthwat', 'sidmasslat', 'sidmassmeltbot',
                  'sidmassmelttop', 'sidmasssi', 'sidmassth', 'sidragtop',
                  'sifb', 'siflcondbot', 'siflcondtop', 'siflfwbot',
                  'siflfwdrain', 'sifllatstop', 'sifllwdtop', 'sifllwutop',
                  'siflsenstop', 'siflsensupbot', 'siflswdtop', 'siflswutop',
                  'sihc', 'simass', 'sipr', 'sirdgconc', 'sirdgthick',
                  'sisaltmass', 'sisnconc', 'sisnhc', 'sisnmass', 'sispeed',
                  'sistrxubot', 'sistryubot', 'sitempbot', 'sitemptop',
                  'sithick', 'sitimefrac', 'sivol', 'sndmassdyn',
                  'sndmassmelt', 'sndmasssi', 'sndmasssnf']},
    ('01.00.17', '01.00.32'): {
        '6hrLev': ['pfull'],
        'Amon': ['fco2antt', 'fco2fos', 'fco2nat'],
        'E3hrPt': ['parasolRefl'],
        'Eday': ['hursminCrop', 'mlotst', 't20d'],
        'Emon': ['sweLut', 'thetaot', 'thetaot2000', 'thetaot300',
                 'thetaot700', 'vegHeight', 'vegHeightPasture',
                 'gppLut', 'hflsLut', 'hfssLut', 'hussLut', 'laiLut', 'nppLut',
                 'rlusLut', 'rsusLut', 'tasLut', 'tslsiLut', 'grassFracC3',
                 'grassFracC4'],
        'EmonZ': ['sltbasin'],
        'Ofx': ['deptho', 'hfgeou'],
        'Omon': ['bfeos', 'bsios', 'chldiatos', 'chlmiscos', 'dfeos',
                 'intdic', 'intpbfe', 'intpbsi', 'intpp', 'intpbn', 'intpbp',
                 'intppdiat',
                 'hfbasin', 'hfbasinpadv', 'hfbasinpmadv', 'hfbasinpmdiff',
                 'htovgyre', 'htovovrt', 'intpcalcite', 'intpoc', 'intppmisc',
                 'masscello', 'msftyzmpa',
                 'no3os', 'o2os', 'o2satos', 'phynos', 'phypos', 'physios',
                 'ponos', 'popos', 'sios',
                 'sltovgyre', 'sltovovrt', 'wmo'],
        'SIday': ['sispeed', 'sitemptop', 'sithick', 'sitimefrac'],
        'SImon': ['sfdsi', 'siage', 'sicompstren', 'sidconcdyn', 'sidconcth',
                  'sidmassdyn', 'sidmassevapsubl', 'sidmassgrowthbot',
                  'sidmassgrowthwat', 'sidmasslat', 'sidmassmeltbot',
                  'sidmassmelttop', 'sidmasssi', 'sidmassth', 'sidragtop',
                  'sifb', 'siflcondbot', 'siflcondtop', 'siflfwbot',
                  'siflfwdrain', 'sifllatstop', 'sifllwdtop', 'sifllwutop',
                  'siflsenstop', 'siflsensupbot', 'siflswdtop', 'siflswutop',
                  'sihc', 'simass', 'sipr', 'sirdgconc', 'sirdgthick',
                  'sisaltmass', 'sisnconc', 'sisnhc', 'sisnmass', 'sispeed',
                  'sistrxubot', 'sistryubot', 'sitempbot', 'sitemptop',
                  'sithick', 'sitimefrac', 'sivol', 'sndmassdyn',
                  'sndmassmelt', 'sndmasssi', 'sndmasssnf']},
}
